// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YAHGA_Server.Database;

namespace YAHGA_Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211004140317_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("YAHGA_Server.Database.Models.FileSystemModel", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Json")
                        .HasColumnType("json");

                    b.HasKey("Guid");

                    b.ToTable("FileSystems");
                });

            modelBuilder.Entity("YAHGA_Server.Database.Models.HostModel", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FileSystemGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Ip")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPlayerGateway")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("OwnerPrivateEntityGuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OwnerPublicEntityGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Guid");

                    b.HasIndex("FileSystemGuid");

                    b.HasIndex("OwnerPrivateEntityGuid");

                    b.HasIndex("OwnerPublicEntityGuid");

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("YAHGA_Server.Database.Models.PlayerModel", b =>
                {
                    b.Property<ulong>("SteamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<Guid?>("EntityGuid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("SteamId");

                    b.HasIndex("EntityGuid");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("YAHGA_Server.Database.Models.PrivateEntityModel", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GivenName")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.HasKey("Guid");

                    b.ToTable("PrivateEntities");
                });

            modelBuilder.Entity("YAHGA_Server.Database.Models.PublicEntityModel", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsGovernmentEntity")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHealthCareProvider")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLawEnforcement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Test")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("PublicEntities");
                });

            modelBuilder.Entity("YAHGA_Server.Database.Models.HostModel", b =>
                {
                    b.HasOne("YAHGA_Server.Database.Models.FileSystemModel", "FileSystem")
                        .WithMany()
                        .HasForeignKey("FileSystemGuid");

                    b.HasOne("YAHGA_Server.Database.Models.PrivateEntityModel", "OwnerPrivateEntity")
                        .WithMany()
                        .HasForeignKey("OwnerPrivateEntityGuid");

                    b.HasOne("YAHGA_Server.Database.Models.PublicEntityModel", "OwnerPublicEntity")
                        .WithMany()
                        .HasForeignKey("OwnerPublicEntityGuid");

                    b.Navigation("FileSystem");

                    b.Navigation("OwnerPrivateEntity");

                    b.Navigation("OwnerPublicEntity");
                });

            modelBuilder.Entity("YAHGA_Server.Database.Models.PlayerModel", b =>
                {
                    b.HasOne("YAHGA_Server.Database.Models.PrivateEntityModel", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityGuid");

                    b.Navigation("Entity");
                });
#pragma warning restore 612, 618
        }
    }
}
